In [1]:
import numpy as np
x = np.arange(9.).reshape(3,3)
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [2]:
np.where(x>5)

(array([2, 2, 2]), array([0, 1, 2]))

In [3]:
x[np.where(x>5)]

array([ 6.,  7.,  8.])

In [4]:
y = np.arange(9.)
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [5]:
x[0]

array([ 0.,  1.,  2.])

In [8]:
pre_shuffle = np.arange(10)

In [11]:
pre_shuffle = pre_shuffle*2
pre_shuffle

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [13]:
indicies = np.random.permutation(10)
indicies

array([3, 0, 8, 7, 6, 5, 1, 2, 9, 4])

In [16]:
shuffled = pre_shuffle[indicies]
shuffled

array([12,  0, 32, 28, 24, 20,  4,  8, 36, 16])