In [1]:
import numpy as np
x = np.arange(9.).reshape(3,3)
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [2]:
np.where(x>5)

(array([2, 2, 2]), array([0, 1, 2]))

In [3]:
x[np.where(x>5)]

array([ 6.,  7.,  8.])

In [4]:
y = np.arange(9.)
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [5]:
x[0]

array([ 0.,  1.,  2.])

In [6]:
pre_shuffle = np.arange(10)

In [7]:
pre_shuffle = pre_shuffle*2
pre_shuffle

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
indicies = np.random.permutation(10)
indicies

array([8, 3, 6, 4, 1, 7, 2, 9, 5, 0])

In [9]:
shuffled = pre_shuffle[indicies]
shuffled

array([16,  6, 12,  8,  2, 14,  4, 18, 10,  0])

In [10]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

In [22]:
x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])