In [1]:
import numpy as np
x = np.arange(9.).reshape(3,3)
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [2]:
np.where(x>5)

(array([2, 2, 2]), array([0, 1, 2]))

In [3]:
x[np.where(x>5)]

array([ 6.,  7.,  8.])

In [4]:
y = np.arange(9.)
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [5]:
x[0]

array([ 0.,  1.,  2.])

In [6]:
pre_shuffle = np.arange(10)

In [7]:
pre_shuffle = pre_shuffle*2
pre_shuffle

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
indicies = np.random.permutation(10)
indicies

array([8, 3, 6, 4, 1, 7, 2, 9, 5, 0])

In [9]:
shuffled = pre_shuffle[indicies]
shuffled

array([16,  6, 12,  8,  2, 14,  4, 18, 10,  0])

In [10]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

In [22]:
x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
def AddTwoNumbers(l1, l2):
    root = [0]
    for i in range (0, len(l1) if len(l1) > len (l2) else len (l2)):
        carry = root.pop()
        root.append(((l1[i] if i < len(l1) else 0) + (l2[i] if  i < len(l2) else 0) + carry) % 10)
        root.append(1 if ((l1[i] if i < len(l1) else 0) + (l2[i] if i < len(l2) else 0) + carry) > 9 else 0)
    return root if root[len(l1) if len(l1) > len (l2) else len (l2)] != 0 else root[0: len(l1) if len(l1) > len (l2) else len (l2)]

In [129]:
l1 = [0, 2, 3]
l2 = [1, 5, 7]
AddTwoNumbers(l1, l2)

[1, 7, 0, 1]

In [130]:
l1 = [0, 9, 3]
l2 = [1, 5, 4]
AddTwoNumbers(l1, l2)

[1, 4, 8]

In [131]:
l1 = [0,9]
l2 = [1,5,4]
AddTwoNumbers(l1, l2)

[1, 4, 5]

In [133]:
l1 = [1,5,4,2,3,4,5]
l2 = [1,3,4,5,6]
AddTwoNumbers(l1,l2)

[2, 8, 8, 7, 9, 4, 5]

In [19]:
root = [0]
root.append(1)
root.pop()

1

In [111]:
root.pop()

0

In [118]:
len(root)

0

In [137]:
import numpy as np
a = np.array([1,2,3,4,5,6])
aOdd = (a%2 == 1)
aOdd

array([ True, False,  True, False,  True, False], dtype=bool)